[project]
name = "learnic"
version = "0.1.0"
description = ""
authors = [
    {name = "Iurii Shikov",email = "115935422+a55le@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "learnic", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
