from typing import Final

TITLE_MAX_LEN: Final = 200
DESCRIPTION_MAX_LEN: Final = 50_000

QA_QUESTION_MAX_LEN: Final = 500
QA_ANSWER_MAX_LEN: Final = 5_000

DURATION_HOURS_MIN: Final = 1
DURATION_HOURS_MAX: Final = 10_000
