from typing import Final

EMAIL_MAX_LEN: Final = 320
FIRST_NAME_MAX_LEN: Final = 100
LAST_NAME_MAX_LEN: Final = 100
PATRONYMIC_MAX_LEN: Final = 100

PASSWORD_MIN_LEN: Final = 12
PASSWORD_MAX_LEN: Final = 128
PASSWORD_HASH_MAX_LEN: Final = 255

DESCRIPTION_MAX_LEN: Final = 10_000
