from typing import Final

COHORT_NAME_MAX_LEN: Final = 200

IANA_TIMEZONE_MAX_LEN: Final = 64
RRULE_MAX_LEN: Final = 1024

CANCELLATION_REASON_MAX_LEN: Final = 1000
RECORDING_URL_MAX_LEN: Final = 2048
SESSION_STREAM_URL_MAX_LEN: Final = 2048
